//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnnotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetApp.Resources.DataAnnotations", typeof(DataAnnotations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerende.
        /// </summary>
        public static string CampEndDate {
            get {
                return ResourceManager.GetString("CampEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J+S-angemeldete Personen.
        /// </summary>
        public static string CampJsPersonsCount {
            get {
                return ResourceManager.GetString("CampJsPersonsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitung, Küche, Hilfspersonen.
        /// </summary>
        public static string CampLeadersTeamCount {
            get {
                return ResourceManager.GetString("CampLeadersTeamCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptleitung.
        /// </summary>
        public static string CampMainLeader {
            get {
                return ResourceManager.GetString("CampMainLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Teilnehmende (TN).
        /// </summary>
        public static string CampParticipantsCount {
            get {
                return ResourceManager.GetString("CampParticipantsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerbeginn.
        /// </summary>
        public static string CampStartDate {
            get {
                return ResourceManager.GetString("CampStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; muss zwischen {1} und {2} liegen..
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; ist erforderlich..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; ist keine gültige E-Mail-Adresse..
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; darf maximal {1} Zeichen lang sein..
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }

        public static string TemplateBudgetName {
            get
            {
                return ResourceManager.GetString("TemplateBudgetName", resourceCulture);
            }
        }

        public static string TemplateBudgetDescription {
            get
            {
                return ResourceManager.GetString("TemplateBudgetDescription", resourceCulture);
            }
        }

        public static string LoginEmail {
            get { return ResourceManager.GetString("LoginEmail", resourceCulture); }
        }

        public static string LoginPassword {
            get { return ResourceManager.GetString("LoginPassword", resourceCulture); }
        }

        public static string RegisterEmail {
            get { return ResourceManager.GetString("RegisterEmail", resourceCulture); }
        }

        public static string RegisterDisplayName {
            get { return ResourceManager.GetString("RegisterDisplayName", resourceCulture); }
        }

        public static string RegisterPassword {
            get { return ResourceManager.GetString("RegisterPassword", resourceCulture); }
        }

        public static string RegisterConfirmPassword {
            get { return ResourceManager.GetString("RegisterConfirmPassword", resourceCulture); }
        }

        public static string PasswordMismatch {
            get { return ResourceManager.GetString("PasswordMismatch", resourceCulture); }
        }

        public static string StringLengthMin {
            get { return ResourceManager.GetString("StringLengthMin", resourceCulture); }
        }

        public static string EmailAlreadyExists {
            get { return ResourceManager.GetString("EmailAlreadyExists", resourceCulture); }
        }

        public static string AddLeader {
            get { return ResourceManager.GetString("AddLeader", resourceCulture); }
        }

        public static string TransactionName {
            get { return ResourceManager.GetString("TransactionName", resourceCulture); }
        }

        public static string TransactionDescription {
            get { return ResourceManager.GetString("TransactionDescription", resourceCulture); }
        }

        public static string TransactionAmount {
            get { return ResourceManager.GetString("TransactionAmount", resourceCulture); }
        }

        public static string TransactionAmountRange {
            get { return ResourceManager.GetString("TransactionAmountRange", resourceCulture); }
        }

        public static string TransactionPerformedBy {
            get { return ResourceManager.GetString("TransactionPerformedBy", resourceCulture); }
        }

        public static string TransactionPaymentSource {
            get { return ResourceManager.GetString("TransactionPaymentSource", resourceCulture); }
        }

        public static string TransactionPaymentMethod {
            get { return ResourceManager.GetString("TransactionPaymentMethod", resourceCulture); }
        }

        public static string ProfileDisplayName {
            get { return ResourceManager.GetString("ProfileDisplayName", resourceCulture); }
        }

        public static string ProfileFirstName {
            get { return ResourceManager.GetString("ProfileFirstName", resourceCulture); }
        }

        public static string ProfileLastName {
            get { return ResourceManager.GetString("ProfileLastName", resourceCulture); }
        }

        public static string ProfileIBAN {
            get { return ResourceManager.GetString("ProfileIBAN", resourceCulture); }
        }

        public static string InviteEmail
        {
            get { return ResourceManager.GetString("InviteEmail", resourceCulture); }
        }

        public static string CategoryName {
            get
            {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }

        public static string CategoryDescription {
            get
            {
                return ResourceManager.GetString("CategoryDescription", resourceCulture);
            }
        }

        public static string SubCategoryName {
            get
            {
                return ResourceManager.GetString("SubCategoryName", resourceCulture);
            }
        }

        public static string SubCategoryDescription {
            get
            {
                return ResourceManager.GetString("SubCategoryDescription", resourceCulture);
            }
        }

        public static string SubCategoryCategoryId {
            get
            {
                return ResourceManager.GetString("SubCategoryCategoryId", resourceCulture);
            }
        }
    }
}
